[tool.black]
line-length = 79
target-version = ["py39"]
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
py_version = 39
line_length = 120

[tool.pyright]
useLibraryCodeForTypes = true
typeCheckingMode = "strict"
pythonVersion = "3.9"
exclude = ["typings"]

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["BMS_ver"]
log_cli = true
log_level = "INFO"
log_cli_format = "%(asctime)s.%(msecs)03d [%(levelname)-8s] %(message)s (%(filename)s:%(lineno)d)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

log_file_level = "INFO"
log_file_format = "%(asctime)s.%(msecs)03d [%(levelname)-8s] %(message)s (%(filename)s:%(lineno)d)"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
markers = [
    "safety",
    "components",
    "setup",
    "ebrix_lite",
    "ebrix_lite_v3",
    "ebrix_lite_80v",
    "eve33v",
    "samsung29e7",
    "samsung48x",
    "micropower",
    "toyota",
    "random_order",
]
